<?xml version="1.0" ?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find ur_description)/urdf/env/box.v2.urdf.xacro" />
  <xacro:include filename="$(find ur_description)/urdf/env/table.urdf.xacro" />
  <xacro:include filename="$(find ur_description)/urdf/env/wall.urdf.xacro" />
  <xacro:include filename="$(find ur_description)/urdf/env/camera.urdf.xacro" />


  <xacro:property name="half_pi" value="1.57079632679" />
  <!-- Definitions of workspace dimensions (world) -->

  <link name="world"/>

  <xacro:generic_wall prefix="top" x="${tx}" y="${wdepth}" z="${wz}"/>
  <xacro:generic_wall prefix="left" x="${wdepth}" y="${ty}" z="${wz}"/>
  <xacro:generic_wall prefix="bottom" x="${tx}" y="${wdepth}" z="${wz}"/>
  <xacro:generic_wall prefix="right" x="${wdepth}" y="${ty}" z="${wz}"/>
  <xacro:table name="table"/>
  <xacro:box_source name="box_1"/>
  <!--<xacro:box_source name="box_2"/>-->
  <!--<xacro:box_source name="box_3"/>-->
  <!--<xacro:box_source name="box_4"/>-->
  <!--<xacro:box_source name="box_5"/>-->
  <!--<xacro:box_source name="box_6"/>-->
  <!--<xacro:box_source name="box_7"/>-->
  <xacro:box_destination name="box_dst"/>


  <joint name="world_top_wall_joint" type="fixed">
    <parent link="world"/>
    <child link="top_wall"/>
    <origin xyz="0 ${ty} 0" rpy="0 0 0"/>
  </joint>

  <joint name="world_left_wall_joint" type="fixed">
    <parent link="world"/>
    <child link="left_wall"/>
    <origin xyz="-${tx + wdepth} ${ty} 0" rpy="0 0 0"/>
  </joint>

  <joint name="world_bottom_wall_joint" type="fixed">
    <parent link="world"/>
    <child link="bottom_wall"/>
    <origin xyz="0 -${0.15} 0" rpy="0 0 0"/>
    <!--<origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>-->
  </joint>

  <joint name="world_right_wall_joint" type="fixed">
    <parent link="world"/>
    <child link="right_wall"/>
    <!--<origin xyz="-${tx} ${ty} 0" rpy="0 0 0"/>-->
    <origin xyz="0.15 ${ty} 0" rpy="0 0 0"/>
    <!--<origin xyz="0 -${0.15} 0" rpy="0 0 0"/>-->
  </joint>

  <joint name="world_camera_obstacle_joint" type="fixed">
    <parent link="world"/>
    <child link="camera_vert_fixation_obstacle_link"/>
    <origin xyz="-0.553 ${ty} 0.0" rpy="0 0 0"/>
  </joint>

  <joint name="world_table_link_joint" type="fixed">
    <parent link="world"/>
    <child link="table"/>
    <origin xyz="-0.0 0.0 0.0" rpy="0 0 0"/>
  </joint>

  <joint name="world_box_1_joint" type="fixed">
    <parent link="world"/>
    <child link="box_1_base"/>
    <origin xyz="-${0.4 + src_box_w / 2} ${0.5 + src_box_h / 2} 0.0" rpy="0 0 0"/>
  </joint>

  <!--<joint name="world_box_1_joint" type="fixed">-->
    <!--<parent link="world"/>-->
    <!--<child link="box_1_base"/>-->
    <!--<origin xyz="-${src_box_w * 0.5} ${ty - src_box_w * 0.5} 0.0" rpy="0 0 ${half_pi}"/>-->
  <!--</joint>-->

  <!--<joint name="world_box_2_joint" type="fixed">-->
    <!--<parent link="world"/>-->
    <!--<child link="box_2_base"/>-->
    <!--<origin xyz="-${src_box_w * 0.5 + src_box_h * 1.0} ${ty - src_box_w * 0.5} 0.0" rpy="0 0 ${half_pi}"/>-->
  <!--</joint>-->

  <!--<joint name="world_box_3_joint" type="fixed">-->
    <!--<parent link="world"/>-->
    <!--<child link="box_3_base"/>-->
    <!--<origin xyz="-${src_box_w * 0.5 + src_box_h * 2.25} ${ty - src_box_w * 0.5} 0.0" rpy="0 0 ${half_pi}"/>-->
  <!--</joint>-->

  <!--<joint name="world_box_4_joint" type="fixed">-->
    <!--<parent link="world"/>-->
    <!--<child link="box_4_base"/>-->
    <!--<origin xyz="-${src_box_w * 0.5 + src_box_h * 2.5} ${ty - src_box_w - src_box_h * 0.5} 0.0" rpy="0 0 0"/>-->
  <!--</joint>-->

  <!--<joint name="world_box_5_joint" type="fixed">-->
    <!--<parent link="world"/>-->
    <!--<child link="box_5_base"/>-->
    <!--<origin xyz="-${src_box_w * 0.5 + src_box_h * 2.5} ${ty - src_box_w - src_box_h * 1.5} 0.0" rpy="0 0 0"/>-->
  <!--</joint>-->

  <!--<joint name="world_box_6_joint" type="fixed">-->
    <!--<parent link="world"/>-->
    <!--<child link="box_6_base"/>-->
    <!--<origin xyz="-${src_box_w * 0.5 + src_box_h * 2.5} ${ty - src_box_w - src_box_h * 2.5} 0.0" rpy="0 0 0"/>-->
  <!--</joint>-->

  <!--<joint name="world_box_7_joint" type="fixed">-->
    <!--<parent link="world"/>-->
    <!--<child link="box_7_base"/>-->
    <!--<origin xyz="${src_box_w * 0.5 - src_box_h * 2.5} ${ty - src_box_w - src_box_h * 0.5} ${tz}" rpy="0 0 0"/>-->
  <!--</joint>-->

  <joint name="world_box_dst_joint" type="fixed">
    <parent link="world"/>
    <child link="box_dst_base"/>
    <origin xyz="-${0.55 + dst_box_h * 0.5} ${0.05 + dst_box_w * 0.5} 0.0" rpy="0 0 ${half_pi}"/>
  </joint>

</robot>

