<?xml version="1.0" ?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find ur_description)/urdf/env/box.v2.urdf.xacro" />
  <xacro:include filename="$(find ur_description)/urdf/env/table.urdf.xacro" />
  <xacro:include filename="$(find ur_description)/urdf/env/wall.urdf.xacro" />
  <xacro:include filename="$(find ur_description)/urdf/env/camera.urdf.xacro" />


  <xacro:property name="half_pi" value="1.57079632679" />
  <xacro:property name="wall_delta" value="0.15" />
  <!-- Definitions of workspace dimensions (world) -->

  <link name="world"/>

  <xacro:generic_wall prefix="top" x="${tx + wall_delta}" y="${wdepth}" z="${wz}"/>
  <xacro:generic_wall prefix="left" x="${wdepth}" y="${ty + wall_delta}" z="${wz}"/>
  <xacro:generic_wall prefix="bottom" x="${tx + wall_delta}" y="${wdepth}" z="${wz}"/>
  <xacro:generic_wall prefix="right" x="${wdepth}" y="${ty + wall_delta}" z="${wz}"/>
  <xacro:table name="table"/>
  <xacro:box_source name="box_1"/>
  <xacro:box_destination name="box_dst"/>


  <joint name="world_top_wall_joint" type="fixed">
    <parent link="world"/>
    <child link="top_wall"/>
    <origin xyz="${wall_delta} ${ty} 0" rpy="0 0 0"/>
  </joint>

  <joint name="world_left_wall_joint" type="fixed">
    <parent link="world"/>
    <child link="left_wall"/>
    <origin xyz="-${tx + wdepth} ${ty} 0" rpy="0 0 0"/>
  </joint>

  <joint name="world_bottom_wall_joint" type="fixed">
    <parent link="world"/>
    <child link="bottom_wall"/>
    <origin xyz="${wall_delta} -${wall_delta} 0" rpy="0 0 0"/>
    <!--<origin xyz="0.0 0.0 0.0" rpy="0 0 0"/>-->
  </joint>

  <joint name="world_right_wall_joint" type="fixed">
    <parent link="world"/>
    <child link="right_wall"/>
    <origin xyz="${wall_delta} ${ty} 0" rpy="0 0 0"/>
    <!--<origin xyz="0 -${0.15} 0" rpy="0 0 0"/>-->
  </joint>

  <joint name="world_camera_obstacle_joint" type="fixed">
    <parent link="world"/>
    <child link="camera_vert_fixation_obstacle_link"/>
    <origin xyz="-0.553 ${ty} 0.0" rpy="0 0 0"/>
  </joint>

  <joint name="world_table_link_joint" type="fixed">
    <parent link="world"/>
    <child link="table"/>
    <origin xyz="-0.0 0.0 0.0" rpy="0 0 0"/>
  </joint>

  <joint name="world_box_1_joint" type="fixed">
    <parent link="world"/>
    <child link="box_1_base"/>
    <origin xyz="-${0.4 + src_box_w / 2} ${0.5 + src_box_h / 2} 0.0" rpy="0 0 0"/>
  </joint>

  <joint name="world_box_dst_joint" type="fixed">
    <parent link="world"/>
    <child link="box_dst_base"/>
    <origin xyz="-${0.55 + dst_box_h * 0.5} ${0.05 + dst_box_w * 0.5} 0.0" rpy="0 0 ${half_pi}"/>
  </joint>

</robot>

