<?xml version="1.0" ?>
<robot name="wall" xmlns:xacro="http://ros.org/wiki/xacro">


<!-- Definition of table dimensions  -->
<xacro:property name="cam_x" value="0.27" />
<xacro:property name="cam_y" value="0.05" />
<xacro:property name="cam_z" value="0.07" />

<material name="black">
  <color rgba="0 0 0 0.8"/>
</material>


<link name="camera_obstacle_link">
  <visual>
    <origin xyz="-${cam_x / 2} ${cam_y / 2} ${cam_z / 2}" rpy="0 0 0"/>
    <geometry>
      <box size="${cam_x} ${cam_y} ${cam_z}"/>
    </geometry>
    <material name="black" />
  </visual>
  <collision>
    <origin xyz="-${cam_x / 2} ${cam_y / 2} ${cam_z / 2}" rpy="0 0 0"/>
    <geometry>
      <box size="${cam_x} ${cam_y} ${cam_z}"/>
    </geometry>
  </collision>
</link>

</robot>